version: "3.8"

services:
  # ===================== MONGO DATABASE =====================
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"                 # Cho phép truy cập MongoDB Compass qua mongodb://root:123@localhost:27017
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://host.docker.internal:27017/shop-pc-api
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  # ===================== BACKEND SERVICE =====================
  backend:
    # --- DÙNG IMAGE CÓ SẴN TRÊN DOCKER HUB ---
    image: nghiatrung/backend:latest

    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - mongo
    env_file:
      - ./envs/backend.env            # chứa JWT_SECRET, PORT,...
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://host.docker.internal:27017/shop-pc-api
    ports:
      - "5000:5000"                   # Map backend ra host (API)
    extra_hosts:
    - "host.docker.internal:host-gateway"
    networks:
      - app-network

  # ===================== FRONTEND SERVICE =====================
  frontend:
    # --- DÙNG IMAGE CÓ SẴN TRÊN DOCKER HUB ---
    image: nghiatrung/frontend:latest
    # --- HOẶC DÙNG SOURCE LOCAL ---
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"                       # Map website ra port 80
    networks:
      - app-network

# ===================== VOLUMES & NETWORKS =====================
volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
